export const en = {
  main_btn: "BECOME A PARTNER",
  main_btn2: "LEARN MORE",
  discover: "Discover our brands",
  main_text:
    "Restaurateur? Join the Taster Platform and rapidly launch one of our iconic virtual restaurant brands from your existing kitchen!",
  head_desc: "The best of street food at home",
  description:
    "Taster is a collection of online restaurants dedicated to bringing the best of street food to you.",
  stats_head: "Bitesize Stats",
  stat_desc1: "Years",
  stat_desc2: "Cheese Slices",
  stat_desc3: "Sweet Potato",
  stat_desc4: "of Noodles",
  stat_desc5: "Tiger Prawns",
  stat_desc6: "Rides",
  element1: "100 Restaurants",
  element2: "25 Cities",
  element3: "5 Brands",
  element4: "And More!",
  we: "Who we are",
  brands: "Our brands",
  contact: "Contact",
  footer_element1: "Our restaurants",
  footer_element2: "Bian Dang",
  footer_element3: "A Burgers",
  footer_element4: "Mission Saigon",
  footer_element5: "Out Fry",
  footer_element6: "Stacksando",
  footer_element7: "Find us",
  footer_element8: "Address",
  footer_element9: `Sorry, we’re just a  digital food court`,
  footer_element10: "Order on",
  footer_element11: "Download on Android",
  footer_element12: "Download on iOS",
  footer_element13: "Corporate",
  footer_element14: "Contact",
  footer_element15: "Our Story",
  footer_element16: "Jobs",
  footer_element17: "Support",
  footer_element18: "Socials",
};
