export const es = {
  main_btn: "CONVERTIRSE EN UN COMPAÑERO",
  main_btn2: "APRENDER MÁS ACERCA DE",
  discover: "Descubre nuestras marcas",
  main_text:
    "¿Restaurador? ¡Únase a Taster Platform y lance rápidamente una de nuestras icónicas marcas de restaurantes virtuales desde su cocina actual!",
  head_desc: "Lo mejor de la comida callejera en casa.",
  description:
    "Taster es una colección de restaurantes en línea dedicados a ofrecerte lo mejor de la comida callejera.",
  stats_head: "Estadísticas de tamaño de bocado",
  stat_desc1: "años",
  stat_desc2: "Lonchas de queso",
  stat_desc3: "batata",
  stat_desc4: "de Fideos",
  stat_desc5: "Langostino tigre",
  stat_desc6: "paseos",
  element1: "100 restaurantes",
  element2: "25 Cities",
  element3: "5 marcas",
  element4: "Y más!",
  we: "Quienes somos",
  brands: "Nuestras marcas",
  contact: "Contacto",
  footer_element1: "Nuestros restaurantes",
  footer_element2: "Bian Dang",
  footer_element3: "Unas hamburguesas",
  footer_element4: "Misión Saigón",
  footer_element5: "Fuera alevines ",
  footer_element6: "Pilando",
  footer_element7: "Encuéntranos",
  footer_element8: "DIRECCIÓN",
  footer_element9: " Lo sentimos, solo somos un patio de comidas digital ",
  footer_element10: "Orden en",
  footer_element11: "Descargar en Android",
  footer_element12: "Descargar en iOS",
  footer_element13: "Corporativo",
  footer_element14: "Contacto",
  footer_element15: "Nuestra historia",
  footer_element16: "Empleos",
  footer_element17: "Apoyo",
  footer_element18: "Sociales",
};
