export const fr = {
  main_btn: "DEVENIR UN PARTENAIRE",
  main_btn2: "APPRENDRE ENCORE PLUS",
  discover: "Découvrez nos marques",
  main_text:
    "Restaurateur? Rejoignez la Plateforme Taster et lancez rapidement l'un de nos marques de restaurants virtuels emblématiques de votre cuisine existante !",
  head_desc: "Le meilleur de la street food à la maison",
  description:
    "Taster est une collection de restaurants en ligne dédiés à vous offrir le meilleur de la cuisine de rue.",
  stats_head: "Statistiques sur la taille des bouchées",
  stat_desc1: "Ans",
  stat_desc2: "Tranches de fromage",
  stat_desc3: "Patate douce",
  stat_desc4: "de nouilles",
  stat_desc5: "Crevettes tigrées",
  stat_desc6: "1 000 000 Manèges",
  element1: "100 restaurants",
  element2: "25 villes",
  element3: "5 marques",
  element4: "Et plus!",
  we: "Qui nous sommes",
  brands: "Nos marques",
  contact: "Contact",
  footer_element1: "Nos restaurants",
  footer_element2: "Bian Dang",
  footer_element3: "Un hamburger",
  footer_element4: "Mission Saïgon",
  footer_element5: "Frire",
  footer_element6: "Stacksando",
  footer_element7: "Trouvez-nous",
  footer_element8: "Adresse",
  footer_element9:
    " Désolé, nous sommes juste un aire de restauration numérique ",
  footer_element10: "Commandez sur",
  footer_element11: "Télécharger sur Android",
  footer_element12: "Télécharger sur iOS",
  footer_element13: "Entreprise",
  footer_element14: "Contact",
  footer_element15: "Notre histoire",
  footer_element16: "Emplois",
  footer_element17: "Soutien",
  footer_element18: "Réseaux sociaux",
};
