export const refs = {
  btn: {
    btn_en: document.querySelector(".en"),
    btn_es: document.querySelector(".es"),
    btn_fr: document.querySelector(".fr"),
    main_btn: document.querySelector(".main_btn"),
    main_btn2: document.querySelector(".main_btn2"),
    discover: document.querySelector(".discover"),
  },
  text: {
    main_text: document.querySelector(".main_text"),
    description: document.querySelector(".description"),
    stat_desc1: document.querySelector(".stat_desc1"),
    stat_desc2: document.querySelector(".stat_desc2"),
    stat_desc3: document.querySelector(".stat_desc3"),
    stat_desc4: document.querySelector(".stat_desc4"),
    stat_desc5: document.querySelector(".stat_desc5"),
    stat_desc6: document.querySelector(".stat_desc6"),
    element1: document.querySelector(".element1"),
    element2: document.querySelector(".element2"),
    element3: document.querySelector(".element3"),
    element4: document.querySelector(".element4"),
    // stat_numb1: document.querySelector(".stat_numb1"),
    // stat_numb2: document.querySelector(".stat_numb2"),
    // stat_numb3: document.querySelector(".stat_numb3"),
    // stat_numb4: document.querySelector(".stat_numb4"),
    // stat_numb5: document.querySelector(".stat_numb5"),
    // stat_numb6: document.querySelector(".stat_numb6"),
  },
  title: {
    head_desc: document.querySelector(".head_desc"),
    stats_head: document.querySelector(".stats_head"),
    we: document.querySelector(".we"),
    brands: document.querySelector(".brands"),
    contact: document.querySelector(".contact"),
  },
};
